apiVersion: v1
kind: Service
metadata:
  name: churn-inference
  labels:
    app: churn-inference
spec:
  type: LoadBalancer
  selector:
    app: churn-inference
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
